<?php

/**
 * Implements hook_theme().
 */
function wmmedia_theme()
{
    $data = [];

    $data['wmmedia.gallery'] = [
        'variables' => [
            '_data' => [],
        ],
        'path' => drupal_get_path('module', 'wmmedia') . '/templates',
        'template' => 'gallery',
        'preprocess functions' => [
            'wmmedia_theme_set_variables',
        ],
    ];

    return $data;
}

function wmmedia_theme_set_variables(&$variables)
{
    // Skip if no data is set or not set as an array
    if (!isset($variables['_data']) || !is_array($variables['_data'])) {
        return;
    }

    $variables = array_merge($variables, $variables['_data']);
    unset($variables['_data']);
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function wmmedia_menu_local_actions_alter(&$local_actions)
{
    if (isset($local_actions['media.add'])) {
        $appearsOn = &$local_actions['media.add']['appears_on'];
        $key = array_search('entity.media.collection', $appearsOn);

        if ($key !== false) {
            unset($appearsOn[$key]);
        }
    }
}
